In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49

In [4]:
a = np.arange(10,40)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

### Invertir el vector

In [5]:
a[::-1]

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [8]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [9]:
a = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
np.argwhere( a!=0 )

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 6],
       [10],
       [11],
       [12],
       [13],
       [14]])

### Crear una matriz identidad de 6x6

In [10]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### Crear una matriz con valores al azar con forma 3x3x3 

In [15]:
r = np.random.random((3,4,5))
r

array([[[0.95203454, 0.76733498, 0.75857819, 0.35144241, 0.14652034],
        [0.02822769, 0.94815269, 0.76700639, 0.68250774, 0.935157  ],
        [0.24485846, 0.02232416, 0.6059293 , 0.28769563, 0.74402311],
        [0.84511793, 0.59443784, 0.31626851, 0.53971067, 0.66528292]],

       [[0.53493008, 0.35942225, 0.97460254, 0.65887475, 0.56356086],
        [0.64265681, 0.58507028, 0.29006418, 0.74532861, 0.82517614],
        [0.72836998, 0.47094621, 0.13618749, 0.66050893, 0.83129221],
        [0.31014369, 0.19743238, 0.56986694, 0.75923477, 0.44702769]],

       [[0.72608017, 0.07629284, 0.79738996, 0.9865209 , 0.25317723],
        [0.22697605, 0.96239108, 0.27805459, 0.86249695, 0.22130661],
        [0.48842201, 0.86444493, 0.73524392, 0.92005102, 0.51930267],
        [0.14787737, 0.01318217, 0.13843387, 0.94501317, 0.59498254]]])

### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [16]:
print( r.argmax() )
print( r.ravel()[r.argmax()] )

print(r)
print(np.unravel_index(r.argmax(), r.shape))
r[np.unravel_index(r.argmax(), r.shape)]

43
0.9865208966366545
[[[0.95203454 0.76733498 0.75857819 0.35144241 0.14652034]
  [0.02822769 0.94815269 0.76700639 0.68250774 0.935157  ]
  [0.24485846 0.02232416 0.6059293  0.28769563 0.74402311]
  [0.84511793 0.59443784 0.31626851 0.53971067 0.66528292]]

 [[0.53493008 0.35942225 0.97460254 0.65887475 0.56356086]
  [0.64265681 0.58507028 0.29006418 0.74532861 0.82517614]
  [0.72836998 0.47094621 0.13618749 0.66050893 0.83129221]
  [0.31014369 0.19743238 0.56986694 0.75923477 0.44702769]]

 [[0.72608017 0.07629284 0.79738996 0.9865209  0.25317723]
  [0.22697605 0.96239108 0.27805459 0.86249695 0.22130661]
  [0.48842201 0.86444493 0.73524392 0.92005102 0.51930267]
  [0.14787737 0.01318217 0.13843387 0.94501317 0.59498254]]]
(np.int64(2), np.int64(0), np.int64(3))


np.float64(0.9865208966366545)

### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [1]:
z = np.ones((11,11))

z[1:-1,1:-1] = 0
z

NameError: name 'np' is not defined

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [20]:
np.tile( np.arange(0,5) , 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Crear dos arreglos al azar A y B, verificar si son iguales

In [24]:
a = np.random.random((3,3))
b = np.random.random((3,3))
print(a,b)
a == b 

[[9.30237686e-01 6.03987084e-01 7.24862315e-01]
 [3.57964080e-01 5.12682093e-04 8.07039579e-01]
 [8.25299467e-01 2.46653099e-01 2.04385393e-01]] [[0.87104696 0.56124237 0.85616951]
 [0.73865543 0.89452871 0.90069308]
 [0.0921534  0.85566974 0.10926386]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [29]:
np.allclose(a,b)  # Con tolerancia, dada por argumentos: rtol atol


False

In [30]:
np.array_equal(a,b)

False